### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by isoz** [Ifera/ScoreHud#133]
Even after setting it to update every 30 seconds, timings still show a large performance hit.

![image](https://user-images.githubusercontent.com/6126350/60915467-d33e4600-a283-11e9-8d9c-e1bad663c073.png)

**Comment by AlexPads** [comment]
how much ram u have 3mb? i dont see this kind of performance and i have it set to 10sec

**Comment by isoz** [comment]
> 
> 
> how much ram u have 3mb? i dont see this kind of performance and i have it set to 10sec

Plese...

**Comment by CkgCam** [comment]
![image](https://user-images.githubusercontent.com/34908523/63316748-1bad5100-c364-11e9-8255-ac95ec6f9000.png)
yea me too

**Comment by JackMD** [comment]
This plugin can die. I don't care.

**Comment by Ifera** [comment]
Hi, please check this now.

**Comment by Ifera** [comment]
Closing due to lack of comments.
