### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by callumrawlinson** [Ifera/ScoreHud#159]
How would you set a countdown timer for example from 5 minutes.

**Comment by callumrawlinson** [comment]
@Ifera

**Comment by Ifera** [comment]
By making an addon for v5.0 or by making a plugin which implements the logic and sends the tags to scorehud to display. There is and won't be a timer addon or plugin tailor made for ScoreHud. If you want it then you are on your own. Use pocketmine forums for further help.
