### ISSUE TITLE
Friends addon ;)

### ISSUE THREAD

**Issue by OguzhanUmutlu** [Ifera/ScoreHud#164]
Hi i am the owner of Friends plugin can you add {friends.friendcount} {friends.requestcount} ?

use OguzhanUmutlu\Friends\Main as FriendsMain;

FriendsMain::getInstance()->getFriends($player);
FriendsMain::getInstance()->getFriendRequests($player);

Thanks!
Discord: Oğuzhan#6561

**Comment by Ifera** [comment]
Please read the wiki. Addons are no longer supported with v6 above. Since you are the author of the plugin, I would suggest you to either provide a separate plugin providing support for ScoreHud tags to your users, or provide support for ScoreHud within your plugin as PiggyFactions has done.

**Comment by Endermanbugzjfc** [comment]
You can make extension plugins with the new ScoreHud API tho (Talking to @OguzhanUmutlu
