### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by Yandura** [Ifera/ScoreHud#165]
07.04 22:07:25 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/ScoreHud.phar/src/Ifera/ScoreHud/libs/jackmd/scorefactory/ScoreFactory" at line 40
07.04 22:07:25 [Server] Server thread/CRITICAL #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
07.04 22:07:25 [Server] Server thread/CRITICAL #1 (): BaseClassLoader->{closure}(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
07.04 22:07:25 [Server] Server thread/CRITICAL #2 (): spl_autoload_call(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
07.04 22:07:25 [Server] Server thread/CRITICAL #3 plugins/ScoreHud.phar/src/Ifera/ScoreHud/utils/Utils(85): class_exists(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
07.04 22:07:25 [Server] Server thread/CRITICAL #4 plugins/ScoreHud.phar/src/Ifera/ScoreHud/ScoreHud(76): Ifera\ScoreHud\utils\Utils::checkVirions()
07.04 22:07:25 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/plugin/PluginBase(116): Ifera\ScoreHud\ScoreHud->onEnable()
07.04 22:07:25 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
07.04 22:07:25 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Ifera\ScoreHud\ScoreHud)
07.04 22:07:25 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Ifera\ScoreHud\ScoreHud)
07.04 22:07:25 [Server] Server thread/CRITICAL #9 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
07.04 22:07:25 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
07.04 22:07:25 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
07.04 22:07:25 [Server] Server thread/CRITICAL #12 pmsrc(11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)

**Comment by Ifera** [comment]
Hmm how did this happen?

**Comment by DarcZera** [comment]
It happened the same way with me, I simply installed the plugin and started the server. at the beginning this error appeared. (pocketmine 1.16.220)

> 

<`10.04` 20:22:16 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/ScoreHud.phar/src/Ifera/ScoreHud/libs/jackmd/scorefactory/ScoreFactory" at line 40
10.04 20:22:16 [Server] Server thread/CRITICAL #0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
10.04 20:22:16 [Server] Server thread/CRITICAL #1 (): BaseClassLoader->{closure}(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
10.04 20:22:16 [Server] Server thread/CRITICAL #2 (): spl_autoload_call(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
10.04 20:22:16 [Server] Server thread/CRITICAL #3 plugins/ScoreHud.phar/src/Ifera/ScoreHud/utils/Utils(85): class_exists(string[52] Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory)
10.04 20:22:16 [Server] Server thread/CRITICAL #4 plugins/ScoreHud.phar/src/Ifera/ScoreHud/ScoreHud(76): Ifera\ScoreHud\utils\Utils::checkVirions()
10.04 20:22:16 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/plugin/PluginBase(116): Ifera\ScoreHud\ScoreHud->onEnable()
10.04 20:22:16 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
10.04 20:22:16 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Ifera\ScoreHud\ScoreHud)
10.04 20:22:16 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Ifera\ScoreHud\ScoreHud)
10.04 20:22:16 [Server] Server thread/CRITICAL #9 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
10.04 20:22:16 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[45] /, string[53] /plugins/)
10.04 20:22:16 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
10.04 20:22:16 [Server] Server thread/CRITICAL #12 pmsrc(11): require(string[81] phar:///jar/1.16.220.phar/src/pocketmine/PocketMine.ph)
10.04 20:22:16 [Server] Server thread/INFO Disabling ScoreHud v6.1.0`>

**Comment by Yandura** [comment]
I downloaded the plugin, put it in the plugin folder and started the server.
The latest update that was done broke scorehub.

**Comment by Ifera** [comment]
Are you downloading the plugin from poggit?

**Comment by galaxytwenty** [comment]
By me Too 

only Download from poggit, put it in Plugins folder

start the server Than CRASH with  
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/ScoreHud.phar/src/Ifera/ScoreHud/libs/jackmd/scorefactory/ScoreFactory" at line 40

**Comment by Ifera** [comment]
Oh right. Your server PHP binaries are outdated. Update your servers PHP binaries to 7.4 or above.

**Comment by DarcZera** [comment]
How?

**Comment by galaxytwenty** [comment]
just download the binaries

**Comment by DarcZera** [comment]
where do i download? where do i install? I dont know

**Comment by Ifera** [comment]
Either use pocketmine forums or pocketmine discord for these queries. This has nothing to do with scorehud.
