### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by DPG896** [Ifera/ScoreHud#166]
What is the tags?

**Comment by Ifera** [comment]
Read the scorehud readme. 
https://github.com/Ifera/ScoreHud#version-60-update

Further, check here for the list of available tags. 
https://github.com/Ifera/ScoreHudX/tree/main/BasicScore
https://github.com/Ifera/ScoreHudX/tree/main/CombatScore
https://github.com/Ifera/ScoreHudX/tree/main/EcoAPIScore
https://github.com/Ifera/ScoreHudX/tree/main/FactionsProScore
https://github.com/Ifera/ScoreHudX/tree/main/PurePermsScore

Read the readme on those repos for the list of available tags.
