### ISSUE TITLE
The scoreboard has rare "ticks"

### ISSUE THREAD

**Issue by UnEnanoMas** [Ifera/ScoreHud#167]
https://www.youtube.com/watch?v=w6JtfNVu_K8

Speed 0.25 for better appreciate it

The truth would be good for you to correct it since it is something very rare

**Comment by Ifera** [comment]
Whats your scorehud version?

**Comment by Ifera** [comment]
Anyways, closing since there is nothing much that can be done about it.
One way could be to remove factions and coordinates from the scoreboard cause these send the most updates to the scoreboard. Removing these should surely make a difference. Other than that, there is no solution at the moment.

**Comment by UnEnanoMas** [comment]
> Whats your scorehud version?

Version I use the latest

**Comment by UnEnanoMas** [comment]
> Anyways, closing since there is nothing much that can be done about it.
> One way could be to remove factions and coordinates from the scoreboard cause these send the most updates to the scoreboard. Removing these should surely make a difference. Other than that, there is no solution at the moment.

Likewise in the previous scorehud, it had it the same and they did not give those rare "ticks", I think you should leave the issue open so that people know that that can happen
