### ISSUE TITLE
When i type the tags, it doesnt work

### ISSUE THREAD

**Issue by DPG896** [Ifera/ScoreHud#168]
![Screenshot_20210413-145437](https://user-images.githubusercontent.com/82310008/115137404-74d7f700-a015-11eb-8d1b-0a60668458b8.png)

**Comment by DPG896** [comment]
The name and online lines are empty

**Comment by Ifera** [comment]
Use [BasicScore](https://poggit.pmmp.io/p/BasicScore/1.1.0) for adding those tags.
