### ISSUE TITLE
ScoreHUD plugin

### ISSUE THREAD

**Issue by Noidenity** [Ifera/ScoreHud#173]
I have a problem using the plugin because when i use the example given {basicscore.name} it just appears blank in game 
![Screenshot_20210425-182425_Minecraft](https://user-images.githubusercontent.com/83180534/116003119-9bd59080-a5f4-11eb-8c6e-25c50882752a.jpg)

**Comment by Ifera** [comment]
Download BasicScore plugin for this. Search it on poggit.
