### ISSUE TITLE
Disable scorehud on specific worlds

### ISSUE THREAD

**Issue by UnEnanoMas** [Ifera/ScoreHud#177]
I wanted to know if it was possible to add scorehud to disable when entering specific worlds.

Some 1vs1 or SkyWars plugins add their own scoreboard to the right, then Scorehud interferes and there is a little scramble to see who shows up.

I would like you to add, if possible, a list of worlds where scorehud is totally disabled

**Comment by Ifera** [comment]
There is this line here in scorehud config where you can specify the scoreboard for set worlds, you could probs use this for doing that.
https://github.com/Ifera/ScoreHud/blob/95b7c0c1a1b0a58cda28224b0f8f7fd80a5a2a4a/resources/scorehud.yml#L79-L95

**Comment by Ifera** [comment]
Anyways I'll probs work on adding the support for what you have asked.

**Comment by Ifera** [comment]
You can use the latest dev build until the release is accepted. add the worlds you want to disable in the disabled-worlds setting of config.yml.

**Comment by RazzyGP** [comment]
how do I set the worlds I want to disable correctly?
