### ISSUE TITLE
Crashes server when useing per world scoreboards

### ISSUE THREAD

**Issue by DragonWizard975** [Ifera/ScoreHud#178]
this is the error that come up when i try to use it
[error.txt](https://github.com/Ifera/ScoreHud/files/6479757/error.txt)

**Comment by EndermanLetsPlay** [comment]
I can confirm this bug.

**Comment by MrNinja008** [comment]
This bug has been fixed in latest dev build

**Comment by Ifera** [comment]
This bug has now been fixed. Please use the latest dev build until the release gets accepted.
