### ISSUE TITLE
{basicscore.name}

### ISSUE THREAD

**Issue by ThatGuy132** [Ifera/ScoreHud#183]
when i do the basicscore.name on the title thing and when i load into the server it dosent work. And i even tried with basicscore.display_name as well.

![16269354616883121714165017433375](https://user-images.githubusercontent.com/87799091/126598227-f276d3a4-b622-47a0-812c-96150fbf6d8b.jpg)

![Screenshot_20210722-023142_Chrome](https://user-images.githubusercontent.com/87799091/126598333-fe98306f-5a5c-4a12-a4d2-0108f18251e6.jpg)

**Comment by Ifera** [comment]
Are you using the BasicScore plugin?

**Comment by Ifera** [comment]
Anyways I cannot reproduce this. Make sure that you are using the BasicScore plugin, you can download the latest dev build from [here](https://poggit.pmmp.io/ci/Ifera/ScoreHudX/BasicScore). If it still doesn't work then reply to this issue with the problem.
