### ISSUE TITLE
Scorehud progress depends on the number of players

### ISSUE THREAD

**Issue by MrBlasyMSK** [Ifera/ScoreHud#184]
#172 

After title:

in lines, if you put the typical animation that the letters light up from left to right or anything like that, it depends on the number of players it goes faster or slower

If there is 1 player, it goes to x1, if there are 2 players, it goes to speed x2 if there are 3 players it goes to speed x3 and so on

If you need to check it out, invite a couple of friends

the update period has to be 1 to make it clearer

**Comment by Ifera** [comment]
a) I dont really understand what you want here.
b) Based on from what I do understand, I am not going to add this since from v6.0, ScoreHud is transitioning away from tasks. What you want will be heavily dependent on it. And thus I won't be adding it.
