### ISSUE TITLE
ScoreHud Crash

### ISSUE THREAD

**Issue by DarrenM999** [Ifera/ScoreHud#186]
PocketMine-MP Crash Dump Sat Aug 14 03:52:46 CDT 2021

Error: Cannot set a score to a player without a scoreboard. Please call ScoreFactory::setScore() beforehand.
File: plugins/ScoreHud.phar/src/Ifera/ScoreHud/libs/jackmd/scorefactory/ScoreFactory
Line: 83
Type: BadFunctionCallException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ScoreHud v6.2.1

Code:
[74] 	public static function hasScore(Player $player): bool{
[75] 		return isset(self::$cache[$player->getRawUniqueId()]);
[76] 	}
[77] 
[78] 	/**
[79] 	 * Set a message at the line specified to the players scoreboard.
[80] 	 */
[81] 	public static function setScoreLine(Player $player, int $line, string $message, int $type = ScorePacketEntry::TYPE_FAKE_PLAYER): void{
[82] 		if(!isset(self::$cache[$player->getRawUniqueId()])){
[83] 			throw new BadFunctionCallException("Cannot set a score to a player without a scoreboard. Please call ScoreFactory::setScore() beforehand.");
[84] 		}
[85] 
[86] 		if($line < self::MIN_LINES || $line > self::MAX_LINES){
[87] 			throw new OutOfBoundsException("Line: $line is out of range, expected value between " . self::MIN_LINES . " and " . self::MAX_LINES);
[88] 		}
[89] 
[90] 		$cache = self::$cache[$player->getRawUniqueId()];
[91] 
[92] 		$entry = new ScorePacketEntry();
[93] 		$entry->objectiveName = $cache->getObjective();

Backtrace:
#0 plugins/ScoreHud.phar/src/Ifera/ScoreHud/scoreboard/Scoreboard(180): Ifera\ScoreHud\libs\jackmd\scorefactory\ScoreFactory::setScoreLine(object pocketmine\Player, integer 1, string[4]     )
#1 plugins/ScoreHud.phar/src/Ifera/ScoreHud/EventListener(110): Ifera\ScoreHud\scoreboard\Scoreboard->display()
#2 plugins/ScoreHud.phar/src/Ifera/ScoreHud/EventListener(92): Ifera\ScoreHud\EventListener->updateTag(object pocketmine\Player, object Ifera\ScoreHud\scoreboard\ScoreTag)
#3 plugins/ScoreHud.phar/src/Ifera/ScoreHud/EventListener(71): Ifera\ScoreHud\EventListener->updateServerTag(object Ifera\ScoreHud\scoreboard\ScoreTag)
#4 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): Ifera\ScoreHud\EventListener->onServerTagUpdate(object Ifera\ScoreHud\event\ServerTagUpdateEvent)
#5 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object Ifera\ScoreHud\EventListener, object Ifera\ScoreHud\event\ServerTagUpdateEvent)
#6 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object Ifera\ScoreHud\event\ServerTagUpdateEvent)
#7 plugins/BasicScore.phar/src/Ifera/BasicScore/listeners/EventListener(38): pocketmine\event\Event->call()
#8 pmsrc/src/pocketmine/scheduler/ClosureTask(61): Ifera\BasicScore\listeners\EventListener->Ifera\BasicScore\listeners\{closure}(integer 3134)
#9 pmsrc/src/pocketmine/scheduler/TaskHandler(137): pocketmine\scheduler\ClosureTask->onRun(integer 3134)
#10 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 3134)
#11 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 3134)
#12 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 3134)
#13 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#14 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#15 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
#16 pmsrc/src/pocketmine/PocketMine(311): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[72] /storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/, string[80] /storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/plugins/)
#17 pmsrc/src/pocketmine/PocketMine(341): pocketmine\server()
#18 pmsrc(11): require(string[127] phar:///storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/P)

PocketMine-MP version: 3.22.1 [Protocol 448]
Git commit: 9477034a4ae58cc5c12b8278c14a8e46a43992b2
uname -a: Linux localhost 4.14.141-g4da0d48 #1 SMP PREEMPT Thu May 13 20:09:45 WIB 2021 aarch64
PHP Version: 7.4.15
Zend version: 3.4.0
OS : Linux, android
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- daverandom/callback-validator unknown@unknown
- pocketmine/binaryutils 0.1.13@0abee38d4e2861621f262c79a2a3d699d8a697f4
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.1.2@9757928424652393b178a3760073113aa7c9911b
- pocketmine/log 0.2.1@830b44a2cf96ef703c550abe64302f230231ca49
- pocketmine/log-pthreads 0.1.3@e477ecf6ec214fdd4415ea1da3fdd9d73bf699ea
- pocketmine/math 0.2.6@43057cb8c179a9859677b496a788db922fd5cfc3
- pocketmine/nbt 0.2.18@9f82ca4d7f97fcd9a566e44b63c4f18a7657ae82
- pocketmine/pocketmine-mp 3.22.1@9477034a4ae58cc5c12b8278c14a8e46a43992b2
- pocketmine/raklib 0.12.11@9cce458b8bfde3e4dfdbf70c659fc7b7fe26b5c4
- pocketmine/snooze 0.1.5@70b5e7937a06878dd321a3182ceb76d56298f2cd
- pocketmine/spl 0.4.2@6b08b7cf8c4afa17139c9a1b3bf1b408531de161

Loaded plugins:
AdminTrollV2 1.2.1 by Rushil13579 for API(s) 3.0.0
Admins 1 by o for API(s) 3.x.x
AntiAuraBot 1.0.1 by  for API(s) 3.0.0
AntiCraft 1.0.0 by refaltor for API(s) 3.0.0
AntiEnchantmentAbuse 1.1.0 by radondev for API(s) 3.0.0
BankUI 1.0.2 by  for API(s) 3.0.0
BasicScore 1.1.0 by Ifera for API(s) 3.0.0
BedcoreProtect 0.10.2 by matcracker for API(s) 3.21.0
ChatFX 1.1.0 by Alacksch for API(s) 3.19.0
CommandLogger 1.0.0 by  for API(s) 3.0.0
CrashAndBan 0.1.2 by jasonwynn10 for API(s) 3.0.0
CustomAreas 1.2.1 by luca28pet for API(s) 3.0.0
DevTools 1.14.2 by PocketMine Team for API(s) 3.13.0
Disguise 1.0.3 by  for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
KygekJoinUI 1.5.1 by Kygekraqmak for API(s) 3.0.0
KygekRanksUI 1.3.0 by Kygekraqmak for API(s) 3.0.0
KygekRulesUI 1.2.0 by Kygekraqmak for API(s) 3.0.0
MaxEnchants 1.2.1 by Xenophilicy for API(s) 3.0.0
MultiWorld 1.6.0-beta3 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.20.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
ScoreHud 6.2.1 by Ifera for API(s) 3.0.0
SeeDevice 0.0.7 by Palente for API(s) 3.0.0
ServerTools 0.3.2 by matcracker for API(s) 3.0.0
Sudo 1 by ErikX for API(s) 3.13.0
VanishV2 2.3 by superbobby for API(s) 3.0.0
WorldGuard 1.1.95 by MihaiChirculete for API(s) 3.0.0
_NewAlias 1.0.5 by Javier Leon9966 for API(s) 3.0.0-ALPHA12, 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

**Comment by Ifera** [comment]
Update your ScoreHud plugin. You're using an old version.
