### ISSUE TITLE
EconomyApi addon doesnt work

### ISSUE THREAD

**Issue by neefee1** [Ifera/ScoreHud#190]
i download EconomyApiAddon.php in plugin_data/ScoreHud/addons, but it doesnt work. I have plugin EcoApiScore, but it updates only after reconnect

**Comment by Ifera** [comment]
addon support was removed. and EcoApiScore is a plugin, so use it like you would use any other plugin.

**Comment by neefee1** [comment]
ok, but ecoapiscore dont updates in real time. To  see changes i need to reconnect
