### ISSUE TITLE
Pocketmine 4 Support

### ISSUE THREAD

**Issue by PocketMiner92** [Ifera/ScoreHud#195]
Is it possible to add Support for Pocketmine 4?
I Hope you can add this.
Thank you very much!

**Comment by thunderfurry** [comment]
**Look in the comments on the [pogit](https://poggit.pmmp.io/p/scoreHud) page**
We all need it lol, when is it coming!

**Comment by supercrafter333** [comment]
This plugin is already supporting PM4. [Click here (PM4)](https://github.com/Ifera/ScoreHud/tree/PM4)

**Comment by HerryYT** [comment]
> This plugin is already supporting PM4. [Click here (PM4)](https://github.com/Ifera/ScoreHud/tree/PM4)

It's just a fork with no changes from PM3.
