### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Tuvqlu** [Ifera/ScoreHud#197]
When I make my leaderboards this happens

This is all my boards:
  "world":
    lines:
    - ""
    - "§l§gGame: §bHub"
    - ""
    - "§8Name: §7{basicscore.name}"
    - ""
    - "§l§cRank: §r{ppscore.rank}
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - "§6§lHub Title: §r{ppscore.prefix}"
    - "§d104.223.99.185"
  "SPACEMURDER":
    lines:
    - ""
    - "§l§gGame: §r§3Murder §bMystery"
    - ""
    - "§8§lName: §r§7{basicscore.name}"
    - ""
    - "§l§cRank: §r{ppscore.rank}
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - "§d104.223.99.185"
  "ComingSoon":
    lines:
    - ""
    - "§l§gGame: §r§3Murder §bHub"
    - ""
    - "§l§8Name: §r§7{basicscore.name}"
    - ""
    - "§l§cRank: §r{ppscore.rank}
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - "§d104.223.99.185"
  "SkyWars":
    lines:
    - "§dName: §5{basicscore.name}"
    - "§dTPS: §5{basicscore.tps}"
    - "§bLoad: §a{basicscore.load}"
  "OrbWars":
    lines:
    - "§dName: §5{basicscore.name}"
    - "§dTPS: §5{basicscore.tps}"
    - "§bLoad: §a{basicscore.load}"
  "Terracraft":
    lines:
    - ""
    - "§l§gGame: §r§6Terra§eCraft"
    - ""
    - "§l§8Name: §r§7{basicscore.name}"
    - ""
    - "§l§5Faction: §r§d{factionmaster.faction.name}"
    - ""
    - "§l§3Coordinates: §r§a{basicscore.x},{basicscore.y},{basicscore.z}"
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - ""
    - "§l§6Title: §r{ppscore.suffix}"
    - "§d104.223.99.185" 
  "Duels":
    lines:
    - ""
    - "§l§6Game: §r§5Duels §dHub"
    - ""
    - "§8§lName: §r§7{basicscore.name}"
    - ""
  "SumoPracticeEverGreene":
    lines:
    - ""
    - "§l§gGame: §r§1Practice §bSB §9Sumo"
    - ""
    - "§l§9Map: §r§1EverGreene"
    - ""
    - "§l§8Name: §r§7{basicscore.name}"
    - ""
    - "§l§1Ping: §r§9{basicscore.ping}"
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - "§d104.223.99.185"
  "KitPvP":
    lines:
    - ""
    - "§l§gGame: §r§1Kit§aPvP"
    - ""
    - "§l§9Map: §r§5Alien §aPlanet"
    - ""
    - "§l§8Name: §r§7{basicscore.name}"
    - ""
    - "§2§lCoins: §r§a{ecoapiscore.money}"
    - ""
    - "§l§aLevel: §r§4[{basicscore.xp_level}]]"
    - ""
    - "§0§lSTATS"
    - "§1Top Killer: §9{advancedeaths.topKiller}"
    - "§2Kills: §a{advanceddeaths.myKills}"
    - "§3KDR: §b{advancedeaths.kdr}"
    - ""
    - "§d104.223.99.185"
...
![image](https://user-images.githubusercontent.com/98550458/154737647-0de2c7b8-dc15-4794-bae4-3f9fbb2fbc06.jpeg)

**Comment by Ifera** [comment]
This is not a plugin error but an error on your end since you format the config incorrectly.

Anyways, upload your `scorehud.yml` file or send a link to that file here.

**Comment by Ifera** [comment]
No worries, and its releasing real soon :)

**Comment by OP-D** [comment]
@Tuvqlu Why are you using AdvanceDeaths tags lol? I still didn’t implement it
