### ISSUE TITLE
Popup?

### ISSUE THREAD

**Issue by SPMP2** [Ifera/ScoreHud#199]
Hi, i have a question, i don’t understand why with this plugin popup doesn’t work 😢

**Comment by Ifera** [comment]
This plugin is meant for providing scoreboards support on servers only. It doesn't deal with popups/title/tips.

**Comment by SPMP2** [comment]
I don’t understand, it’s is because i have installed this plugin, all my popup doesn’t work now ? Or it is not this plugin ? Please ..

**Comment by Ifera** [comment]
Not caused by this plugin.
