### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Ezinox** [Ifera/ScoreHud#202]
hey! you can add "RankSyseme plugin" ? in scorehud please ?

**Comment by ItsToxicGG** [comment]
> hey! you can add "RankSyseme plugin" ? in scorehud please ?

Hi, so if the owner which is Ifera and does not do this, ill think about doing a scorehud plugin for ranksystem

**Comment by Ifera** [comment]
> hey! you can add "RankSyseme plugin" ? in scorehud please ?
Sorry, please ask the owner of the plugin to integrate ScoreHud support into their plugin.
